// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strconv"
	"strings"
)

type hTTPShadow struct {
	Bind *string `json:"bind" toml:"bind" yaml:"bind"`
	Port *int    `json:"port" toml:"port" yaml:"port"`
}
type configShadow struct {
	LogLevel *string     `json:"log-level" toml:"log-level" yaml:"log-level"`
	HTTP     *hTTPShadow `json:"http" toml:"http" yaml:"http"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.HTTP.Bind = "[::]"
	set("http.bind", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Bind != nil {
			cfg.HTTP.Bind = *s.HTTP.Bind
			set("http.bind", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "log-level"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = LogLevel(v)
			set("log-level", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "bind"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.Bind = v
			set("http.bind", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "http.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.HTTP.Port = int(p)
			set("http.port", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"log-level"}, o.Separator), strings.Join([]string{"http", "bind"}, o.Separator), strings.Join([]string{"http", "port"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"log-level"}, o.Separator), "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.String(strings.Join([]string{"http", "bind"}, o.Separator), "[::]", "Address to listen on")
	fs.Int(strings.Join([]string{"http", "port"}, o.Separator), 8080, "Port to listen on")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "bind"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.bind",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		case "http":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub hTTPShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

func (s *hTTPShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Bind = &str
			default:
				return fmt.Errorf("bind: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*hTTPShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("log-level = %v\n", c.LogLevel))
	b.WriteString(fmt.Sprintf("http.bind = %v\n", c.HTTP.Bind))
	b.WriteString(fmt.Sprintf("http.port = %v\n", c.HTTP.Port))
	return b.String()
}
