name: Config docs

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  config-docs:
    permissions:
      contents: read
    uses: USA-RedDragon/reusable-actions/.github/workflows/configulator-docs.yaml@d2474932549b3213defffc832aa0950ea2c48e48 # v2.0.33
    with:
      dir: internal/config
      type: Config
      app-id: ${{ vars.AUTO_COMMIT_APP_ID }}
    secrets:
      app-key: ${{ secrets.AUTO_COMMIT_APP_KEY }}
